### ISSUE TITLE
[Fabric 1.19.2] Can't summon slime golem

### ISSUE THREAD

**Issue by kingkuys2123** [FireMuffin303/Muffins-SlimeGolem#1]
Fabric 0.14.12
Muffin's Slime Golem 1.0.2
Fabric API 0.72.0
Java 8 Update 351
Architectury 6.4.62

https://user-images.githubusercontent.com/114457180/212627416-d0357c3e-8f14-4996-b03f-93521cd34f05.mp4

**Comment by FireMuffin303** [comment]
I see there some golems from other mod from your video, could I know the name of those golem mod please? Since it might conflicted to each other.

**Comment by kingkuys2123** [comment]
Stone Golem => [**BiomeMakeover**](https://www.curseforge.com/minecraft/mc-mods/biome-makeover)
Clay Golem => [**ItTakesAPillage**](https://www.curseforge.com/minecraft/mc-mods/it-takes-a-pillage-fabric)
Iron Golem, Snow Golem => **MineCraft**
Copper Golem => [**FriendsAndFoes**](https://www.curseforge.com/minecraft/mc-mods/friends-and-foes)
Tuff Golem => [**MobVote2022**](https://www.curseforge.com/minecraft/mc-mods/mob-vote-2022)

[Mods List](https://pastebin.com/0StA8Mvj)

**Comment by FireMuffin303** [comment]
So I have been checking every golem mods you gave me, [Mobvote2022](https://www.curseforge.com/minecraft/mc-mods/mob-vote-2022) is the cause of it.
I decomplied the mod and check trySpawnGolem method inside the CarvedPumpkinMixin class. 

The method will check Iron Golem, Snow Golem and Tuff Golem structure to spawn certain golem (which is unnecessary to check Iron Golem and Snow Golem structure when using mixin inject) then cancel to whole method, causing other mods that sharing the same method to check and spawn golem never have a opportunity to run. 

This also affect [Straw Golem](https://www.curseforge.com/minecraft/mc-mods/straw-golem-reborn) mod to not working as well.

Copper Golem from [FriendsAndFoes](https://www.curseforge.com/minecraft/mc-mods/friends-and-foes) is using Lighting Rod to check copper golem structure instead of Carved Pumpkin so this mod is not conflict

Golem from [BiomeMakeover](https://www.curseforge.com/minecraft/mc-mods/biome-makeover) will cancel the method only when golem structure its detect is from the mod itself.

Clay Golem from [It Takes a Pillage](https://www.curseforge.com/minecraft/mc-mods/it-takes-a-pillage-fabric) doesn't using mixin class for checking golem structure and spawn it. so it not conflict.

**Comment by kingkuys2123** [comment]
Okayy, thanks! :)
